### PR TITLE
Updating to Apache Commons Lang 3

### PR DESCRIPTION
**Pull request by Thunderforge**
I've set it to Apache Commons Lang 3.1 because that's [the last version to support Java 5](https://commons.apache.org/proper/commons-lang/release-history.html), and [the Jackcess FAQ says that's a requirement](http://jackcess.sourceforge.net/faq.html#jdk). I suppose this means that it will break the patches that allow it to work on Java 1.4.

When this project requires Java 6 or 7, upgrading to newer versions of Apache Commons Lang 3.x will be as easy as updating the pom.xml file.

### CODE REVIEW

**Comment by Thunderforge** [comment]
@jahlborn Can this pull request be accepted? Or do I need to figure out how to submit it on SourceForge?

**Comment by jahlborn** [comment]
Sorry, this is effectively a breaking change for current users of the library.  This would have to be rolled into a non-minor release.  I've contemplated making such a change, but haven't been ready to pull the trigger yet.

**Comment by Thunderforge** [comment]
@jahlborn I'm surprised that there are still users who are using pre-Java 5 code. Or is it a breaking change for some other reason?

**Comment by jahlborn** [comment]
it's a breaking change because a simple upgrade of the jackcess would fail unless you updated the dependent libraries (which may or may not cause other issues).  i try very hard to keep minor versions "drop-in" compatible.

**Comment by Thunderforge** [comment]
Wouldn't Maven or Gradle or whatever they're using automatically pull down the new version? Or do clients still just drop jars into a libs folder?

If it won't be included in the next version, will it be included in any future version?

**Comment by jahlborn** [comment]
not everybody uses something with automatic dependency management.  also, pulling in new dependencies can have other negative affects if it causes other conflicts.

i will probably look to do this at some point in time in a non-patch release.

**Comment by tballison** [comment]
Robert Munteanu recently opened https://issues.apache.org/jira/browse/TIKA-2756 to ask that we remove our dependency on commons-lang.  Jackcess is our only dependency that requires it.  Is upgrading to lang3 still a non-starter for Jackcess?  Thank you!

**Comment by jahlborn** [comment]
I'm in the midst of some expression evaluation changes right now.  after that stuff is settled, i'll try to evaluate the upgrade dependencies and/or upgrade java versions situation.

**Comment by Thunderforge** [comment]
> There is always the option of embedding the dependencies in your jar and renaming to avoid conflicts using the maven shade plugin.

@rombert I'd prefer that we not try to embed dependencies inside jars. That means that consumers have no control over whether or not the jar is included, and if a security vulnerability were discovered in Commons Lang 2.x, then it can't be patched (I've had that happen with jars embedding encryption libraries, which are definitely not the things you want to be unable to upgrade).

In the mean time, I've updated this PR so that it can merge cleanly into master. Upgrading to Apache Commons Lang 3.x would be the best solution in my opinion.

(As an FYI, I had to downgrade my JDK to 8 because JDK 11 can't compile to Java 5. I do hope that we increase the minimum at some point in the future).

**Comment by rombert** [comment]
Thanks for the quick turnaround @Thunderforge ! I was only suggestiong the shade option to make it easier to upgrade. If you're OK with switching to commons-lang3 that is even better for us.

**Comment by Thunderforge** [comment]
> If you're OK with switching to commons-lang3 that is even better for us.

That’s why I created this PR in the first place over a year ago 😉Hopefully the project maintainers agree.

**Comment by gordthompson** [comment]
@jahlborn - When you do contemplate a major version bump please consider going all the way to Java 8. That would let us use java.time.LocalDateTime and finally free us from the legacy annoyances of java.util.Date. Obviously you are more than welcome to use my mods from [jackcess8](https://github.com/gordthompson/jackcess/tree/jackcess8?files=1) if they would be helpful.

**Comment by J-cztery** [comment]
Apache commons-lang does not work on java10. It's SystemUtils tries to parse java version and fails. That is the reason why we do not want to have it anywhere in our dependency chain and jackcess is the only reason we still have it!
Please do something about it.

**Comment by jahlborn** [comment]
Sorry, i forgot about this pull request.  Short answer is that this will be fixed in Jackcess 3.0.  Please follow the feature request here: https://sourceforge.net/p/jackcess/feature-requests/35/

**Pull request closed without merging**
