### PR TITLE
Replace usage of Apache commons-lang3 by compact custom implementations

### PR DESCRIPTION
**Pull request by spannm**
jackcess depends on `org.apache.commons:commons-lang3` but uses that library only to a small extent.
commons-lang3 is a large library for String-related functionality. The jar is rather heavy - it weighs in at about 500 kB or more depending on version.

**This pull request makes jackcess fully independent from commons-lang3**

- add a light-weight ToStringBuilder to the library that produces toString output exactly as before with lang3
- introduce a small number of static String/CharSequence-handling methods in new class StringUtil (isBlank, trimToNull, reflectionToString etc.)

**Dependencies Before**:

```
mvn dependency:tree -Dscope=compile
..
[INFO] --- dependency:3.6.1:tree (default-cli) @ jackcess ---
[INFO] com.healthmarketscience.jackcess:jackcess:jar:4.0.6-SNAPSHOT
[INFO] +- org.apache.commons:commons-lang3:jar:3.10:compile
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] \- org.apache.poi:poi:jar:4.1.1:compile
[INFO]    +- commons-codec:commons-codec:jar:1.13:compile
[INFO]    +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO]    \- org.apache.commons:commons-math3:jar:3.6.1:compile

```
**Dependencies After**:

```
mvn dependency:tree -Dscope=compile
..
[INFO] --- dependency:3.6.1:tree (default-cli) @ jackcess ---
[INFO] com.healthmarketscience.jackcess:jackcess:jar:4.0.6-SNAPSHOT
[INFO] +- commons-logging:commons-logging:jar:1.2:compile
[INFO] \- org.apache.poi:poi:jar:4.1.1:compile
[INFO]    +- commons-codec:commons-codec:jar:1.13:compile
[INFO]    +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO]    \- org.apache.commons:commons-math3:jar:3.6.1:compile

```

### CODE REVIEW

**Comment by jahlborn** [comment]
I'm pretty sure a similar request was made before (i looked but couldn't find it).  i think commons-lang3 is a reasonable dependency despite its relatively small usage. 500kb really isn't a big deal in this day and age.  If you really need a smaller jar, i'd suggest creating a custom apache commons-lang3 jar with just the necessary classes (there are maven plugins which can do this pretty easily).

**Comment by spannm** [comment]
jackcess does not have a compelling reason to rely on commons-lang3
It makes very limited use of it, much of which can be covered by JDK functionality.

There is great value in depending on as few as possible external resources, as it reduces or avoids dependency maintenance responsibilities, security issues, future incompatibilities, Java version dependence, component weight, and license considerations.

jackcess could even become completely independent
I think that would be awesome

**Comment by jahlborn** [comment]
> reduces or avoids maintenance responsibilities, security issues, future incompatibilities

these same arguments could be made _for_ depending on third party libraries and not "rolling your own". the apache commons libraries are used by tons of other projects.  i'd much rather rely on their battle tested code instead of adding additional maintenance burden for this library.  like i said, if code footprint is truly a burden, then it's not too hard to create some custom "slim" jars for third party deps which only contain the necessary classes.

> jackcess could even become completely independent

i do appreciate the value of that.  i actually did make a transition like that in another library i maintain for similar reasons (although in that case the code was coming a third library i maintained).  in this case, however, it is adding a fair bit of new code (that will need to be maintained) from a very popular and well maintained third party library.  i just don't see the costs outweighing the benefits here.

**Comment by spannm** [comment]
Have you looked at the PR and realize how little of commons-lang3 we actually use?

**Comment by jahlborn** [comment]
> Have you looked at the PR and realize how little of commons-lang3 we actually use?

i have, and i see 500+ lines of new code (including tests) as well as a thread local, holding a weak hash map.  not exactly trivial code.

**Comment by spannm** [comment]
Fair point about the `ThreadLocal`. A map suffices in `ToStringBuilder` to avoid cycles. Pull request updated.

> i see 500+ lines of new code (including tests)

244 lines of new code excluding tests ;)

```
mvn io.github.orhankupusoglu:sloc-maven-plugin:sloc
+---------------+----------------------+----------+----------+----------+----------+----------+----------+
| Package Name  | File Name            | Type     | Blank    | JavaDoc  | Comment  | Code     | Total    |
+---------------+----------------------+----------+----------+----------+----------+----------+----------+
[..]
| jackcess.util | StringUtil.java      | src      |       14 |       59 |        0 |       89 |      162 |
| jackcess.util | StringUtilTest.java  | test     |       12 |        0 |        0 |       68 |       80 |
| jackcess.util | ToStringBuilder.java | src      |       21 |        5 |        0 |      155 |      181 |
[..]
+---------------+----------------------+----------+----------+----------+----------+----------+----------+
| 9 package(s)  | 235 file(s)          | java     |    10057 |     8276 |     5590 |    45335 |    69258 |
+---------------+----------------------+----------+----------+----------+----------+----------+----------+
```

Most of the new code is to replicate the ToString stuff that previously came from commons-lang3.
Any IDE will happily generate pretty decent `toString` methods.
One could argue why the special toString representations and overhead of pulling in an external lib just for that job?

> i don't see a real "problem" being solved here.

I do not see commons-lang3 solving a real problem in jackcess.
Please take another look. I would appreciate if you reconsidered.

**Comment by jahlborn** [comment]
> I do not see commons-lang3 solving a real problem in jackcess. Please take another look. I would appreciate if you reconsidered.

the problem being solved is that i don't need to write or maintain any of that code, as i've already outlined above.

**Pull request closed without merging**
